# ATTENTION

# Transition config settings

# ReadConsistency is the consistency of the plot package
# WriteConsistency is the consistency of the collector package

# The keyspace package still uses the cassandraAdmin consistency
# and the udpError package still uses the cassandra consistency
# The idea is to change the cassandra gobol package to accept
# multiple consistencies and abstract that to the applications

# BE CAREFUL!!! There are, for now, FOUR consistency settings

ReadConsistency = [
  "quorum",
  "one"
]

WriteConsisteny = [
  "quorum",
  "one"
]

# MaxConcurrentTimeseries CANNOT BE BIGGER THAN MaxConcurrentReads
# Max number of concurrent timeseries being processed
MaxConcurrentTimeseries = 50

# Max number of concurrent read queries on cassandra
MaxConcurrentReads = 100

# Max number of timeseries allowed to be queried
MaxTimeseries = 5000

# Warning number of timeseries
LogQueryTSthreshold = 1000

BoltPath = "/tmp/mycenae/cache.db"
WALPath = "/tmp/mycenae/wal"

# Max number of concurrent points being processed
MaxConcurrentPoints = 1000

# Max number of concurrent bulk requests to elasticsearch
MaxConcurrentBulks = 1

# Number, in bytes of bulk playload
MaxMetaBulkSize = 1000000

# Number of points in buffer
MetaBufferSize = 100000

MetaSaveInterval = "1s"

MaxRateLimit = 20

Burst = 100

CompactionStrategy = "TimeWindowCompactionStrategy"

[logs]
  logLevel = "DEBUG"
  environment = "QA"

[cluster]
  port = 6969
  checkInterval = "1s"
  applyWait = 50
  [cluster.consul]
    address = "localhost.consul.macs.intranet"
    port = 8500
    cert = "/tmp/mycenae/agent.cert"
    key  = "/tmp/mycenae/agent.key"
    ca   = "/tmp/mycenae/ca.cert"
    service = "mycenae"
    tag = "http"
    token = "866239fd-5129-92d2-4a09-3e7355f7bf38"


[cassandra]
  keyspace = "mycenae"
  consistency = "one"
  nodes = ["172.17.0.3","172.17.0.4","172.17.0.5"]
  username = "cassandra"
  password = "cassandra"
  connections = 3
  discoverHosts = true
  discoverySleep = 10
  retry = 5
  pageSize = 5000
  timeout = "60s"
  protoVersion = 4

[TTL]
  max = 90

[UDPserver]
  port = "4242"
  readBuffer = 1048576

[UDPserverV2]
  port = "4243"
  readBuffer = 1048576

[HTTPserver]
  path = "/"
  port = "8787"
  bind = "localhost"

[stats]
  address = "0.0.0.0"
  port = "4243"
  protocol = "udp"
  ksid = "stats"
  ttl = "5"
  interval = "@every 1m"
  runtime = true
  [stats.tags]
    service = "mycenae"

[probe]
  threshold = 0.5

[elasticSearch]
  index = "ts"
  [elasticSearch.cluster]
    type = "weighted"
    seed = "172.17.0.6:9200"
    timeout = 15